<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <TypeScriptToolsVersion>3.4</TypeScriptToolsVersion>
	<PreserveCompilationContext>true</PreserveCompilationContext>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ClientApp\src\app\configuracao-email\objetos.ts" />
    <None Remove="ClientApp\src\app\etiquetas\objetos.ts" />
    <None Remove="ClientApp\src\app\mensagens-email-inscricao\objetos.ts" />
    <None Remove="ClientApp\src\app\contratos-inscricao\objetos.ts" />
    <None Remove="ClientApp\src\app\divisao-oficinas\objetos.ts" />
    <None Remove="ClientApp\src\app\divisao-quartos\objetos.ts" />
    <None Remove="ClientApp\src\app\divisao-salas-estudo\objetos.ts" />
    <None Remove="ClientApp\src\app\estatisticas\objetos.ts" />
    <None Remove="ClientApp\src\app\inscricao\atividades\comp-departamentos.ts" />
    <None Remove="ClientApp\src\app\inscricao\atividades\comp-oficinas.ts" />
    <None Remove="ClientApp\src\app\inscricao\atividades\comp-salas.ts" />
    <None Remove="ClientApp\src\app\inscricao\atividades\comp-sarau.ts" />
    <None Remove="ClientApp\src\app\inscricao\comp-form-inscricao-infantil.ts" />
    <None Remove="ClientApp\src\app\inscricao\comp-form-inscricao.ts" />
    <None Remove="ClientApp\src\app\inscricao\dlg-selecao-inscricao-adulto.ts" />
    <None Remove="ClientApp\src\app\inscricao\objetos.ts" />
    <None Remove="ClientApp\src\app\departamentos\objetos.ts" />
    <None Remove="ClientApp\src\app\inscricao\pagamento\comp-pagamento.ts" />
    <None Remove="ClientApp\src\app\inscricao\tela-inscricao-infantil.ts" />
    <None Remove="ClientApp\src\app\inscricao\tela-inscricao.ts" />
    <None Remove="ClientApp\src\app\oficinas\objetos.ts" />
    <None Remove="ClientApp\src\app\quartos\objetos.ts" />
    <None Remove="ClientApp\src\app\sala-estudo\objetos.ts" />
    <None Remove="ClientApp\src\app\sarais\objetos.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-configuracao-email.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-contratos-inscricao.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-departamentos.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-divisao-oficinas.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-divisao-quartos.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-divisao-salas.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-estatisticas.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-etiquetas.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-inscricoes.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-mensagens-email-inscricao.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-oficinas.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-quartos.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-relatorios.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-salas.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-sarais.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-usuarios-adm.ts" />
    <None Remove="ClientApp\src\app\webservices\webservice-usuarios-comum.ts" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.1" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.7.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="MySql.Data" Version="9.2.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventoWeb.Nucleo\EventoWeb.Nucleo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="ClientApp\src\app\configuracao-email\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\etiquetas\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\mensagens-email-inscricao\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\contratos-inscricao\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\divisao-oficinas\objetos.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\app\divisao-quartos\objetos.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\app\divisao-salas-estudo\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\estatisticas\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\atividades\comp-departamentos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\atividades\comp-oficinas.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\atividades\comp-salas.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\atividades\comp-sarau.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\comp-form-inscricao-infantil.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\comp-form-inscricao.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\dlg-selecao-inscricao-adulto.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\departamentos\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\pagamento\comp-pagamento.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\tela-inscricao-infantil.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\inscricao\tela-inscricao.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\oficinas\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\quartos\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\sala-estudo\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\sarais\objetos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-configuracao-email.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-mensagens-email-inscricao.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-divisao-oficinas.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-divisao-quartos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-etiquetas.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-usuarios-comum.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-usuarios-adm.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-sarais.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-relatorios.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-inscricoes.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-divisao-salas.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-oficinas.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-quartos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-estatisticas.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-contratos-inscricao.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-departamentos.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\webservices\webservice-salas.ts" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="ClientApp\tsconfig.app.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="ClientApp\tsconfig.spec.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="hibernate.cfg.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties clientapp_4tsconfig_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
